# Generated by Django 4.1.3 on 2023-07-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_participant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('members', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
