# Generated by Django 4.1.3 on 2023-07-24 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_members_team_solution_team_is_winner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.CharField(default='', max_length=255),
        ),
    ]
