# Generated by Django 4.1.3 on 2023-07-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='code',
            new_name='solution_code',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_reviewed',
        ),
    ]
