# Generated by Django 4.1.3 on 2023-07-24 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_team_is_winner_remove_team_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
