# Generated by Django 4.1.3 on 2023-07-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_submission_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
