# Generated by Django 4.1.3 on 2023-07-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_submission_is_reviewed_alter_submission_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='solution_code',
            field=models.TextField(default="''"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.DeleteModel(
            name='Submission',
        ),
    ]
