# Generated by Django 4.1.3 on 2023-07-25 04:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_solution_code_team_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.get_current_timezone),
        ),
    ]
