# Generated by Django 4.1.3 on 2023-07-25 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_team_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
