# Generated by Django 4.1.3 on 2023-07-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_round2submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='is_winner',
        ),
        migrations.RemoveField(
            model_name='team',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='team',
            name='submission_time',
        ),
    ]
