# Generated by Django 4.1.3 on 2023-07-25 05:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_team_is_winner_remove_team_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
