# Generated by Django 4.1.3 on 2023-07-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_team_submission_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='round2submission',
            old_name='submission_code',
            new_name='participant_code',
        ),
        migrations.RemoveField(
            model_name='round2submission',
            name='submission_time',
        ),
    ]
