# Generated by Django 4.1.3 on 2023-07-25 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_rename_submission_code_round2submission_participant_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='round2submission',
            name='submission_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
